site_name: Open-Source AI Software Craft
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - tags

nav:
  - Home: index.md
  - Tags: tags.md
  - Aider: aider.md
  - Cline: cline.md
  - Codex CLI: codex-cli.md
  - Continue: continue.md
  - Gemini CLI: gemini-cli.md
  - GitHub Copilot Chat: github-copilot-chat.md
  - LLM: llm.md
  - OpenCode: open-code.md
  - OpenHands: open-hands.md
  - Refact: refact.md
  - RooCode: roocode.md
  - Ruler: ruler.md
