site_name: Open-Source AI Software Craft
nav:
  - Home: index.md
  - Aider: aider.md
  - Cline: cline.md
  - Codex CLI: codex-cli.md
  - Continue: continue.md
  - Gemini CLI: gemini-cli.md
  - GitHub Copilot Chat: github-copilot-chat.md
  - LLM: llm.md
  - OpenCode: open-code.md
  - OpenHands: open-hands.md
  - Refact: refact.md
  - RooCode: roocode.md
  - Ruler: ruler.md