site_name: Open-Source AI Software Craft
theme:
  name: material
  custom_dir: custom_theme
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.indexes
  language: en
  palette:
    - scheme: default
      primary: 'custom'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: 'custom'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags:
      tags_file: tags.md

nav:
  - Home: index.md
  - Tools:
    - Aider: aider.md
    - Cline: cline.md
    - Codex CLI: codex-cli.md
    - Continue: continue.md
    - Gemini CLI: gemini-cli.md
    - GitHub Copilot Chat: github-copilot-chat.md
    - LLM: llm.md
    - OpenCode: open-code.md
    - OpenHands: open-hands.md
    - Refact: refact.md
    - RooCode: roocode.md
    - Ruler: ruler.md
  - All Tags: tags.md
