site_name: Open-Source AI Software Craft
theme:
  name: material
  custom_dir: custom_theme
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: 'custom'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: 'custom'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags:
      tags_file: tags.md

nav:
  - Home: index.md
  - CLI Tools: tags/#cli
  - GUI Tools: tags/#gui
  - VS Code Extensions: tags/#vscode
  - All Tags: tags.md
