name: docs
on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - run: pip install mkdocs mkdocs-material
      - run: mkdocs build --strict --site-dir site

      - run: echo oss-ai-swe.org > site/CNAME

      - uses: actions/upload-pages-artifact@v3
        with: { path: ./site }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/deploy-pages@v4
